version = "1.0"
created_at = "2025-06-17T13:54:27.517424"

[prediction]
target_stats = [ "points", "rebounds", "assists",]
min_games_for_prediction = 5
confidence_threshold = 0.6
max_uncertainty = 10.0
lookback_games = 5
min_games_for_stats = 3

[data]
base_url = "https://www.basketball-reference.com/wnba"
rate_limit_delay = 2.0
max_retries = 3
user_agent = "WNBA-Analytics-Bot/1.0"
data_dir = "wnba_game_data"
output_dir = "wnba_predictions"
model_dir = "wnba_models"
validation_dir = "wnba_validation"
timeout_seconds = 30

[validation]
test_weeks = 4
min_train_weeks = 8
step_weeks = 2
n_validation_periods = 10
target_brier_score = 0.12
min_r2_score = 0.5
target_coverage = 0.95
early_stopping_patience = 3

[dashboard]
page_title = "WNBA Daily Game Predictions"
page_icon = "🏀"
layout = "wide"
initial_sidebar_state = "expanded"
default_confidence_threshold = 0.7
show_uncertainties = true
auto_refresh_minutes = 60
max_players_display = 12

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
log_file = "wnba_predictions.log"
max_log_size_mb = 10
backup_count = 5
enable_performance_logging = true
log_predictions = false

[models.weights]
xgboost = 0.3
lightgbm = 0.25
random_forest = 0.25
neural_network = 0.2

[models.xgboost]
n_estimators = 100
max_depth = 6
learning_rate = 0.1
random_state = 42
verbosity = 0

[models.lightgbm]
n_estimators = 100
max_depth = 6
learning_rate = 0.1
random_state = 42
verbosity = -1

[models.random_forest]
n_estimators = 100
max_depth = 8
random_state = 42
n_jobs = -1

[models.neural_network]
hidden_dims = [ 128, 64, 32, 16,]
dropout_rate = 0.3
learning_rate = 0.001
max_epochs = 100
patience = 15
batch_size = 32
