server.fileWatcherType = "poll"
browser.gatherUsageStats = false
# WNBA Prediction System Configuration

[prediction]
# Target statistics to predict
target_stats = ["points", "total_rebounds", "assists"]

# Model configuration
min_games_for_prediction = 5
confidence_threshold = 0.6
max_uncertainty = 10.0

# Feature engineering
lookback_games = 5
min_games_for_stats = 3

[models]
# Model ensemble weights
[models.weights]
xgboost = 0.30
lightgbm = 0.25
random_forest = 0.25
neural_network = 0.20

# XGBoost parameters
[models.xgboost]
n_estimators = 100
max_depth = 6
learning_rate = 0.1
random_state = 42

# LightGBM parameters
[models.lightgbm]
n_estimators = 100
max_depth = 6
learning_rate = 0.1
random_state = 42

# Random Forest parameters
[models.random_forest]
n_estimators = 100
max_depth = 8
random_state = 42
n_jobs = -1

# Neural Network parameters
[models.neural_network]
hidden_dims = [128, 64, 32, 16]
dropout_rate = 0.3
learning_rate = 0.001
max_epochs = 100
patience = 15
batch_size = 32

[data]
# Data fetching configuration
base_url = "https://www.basketball-reference.com/wnba"
rate_limit_delay = 2.0
max_retries = 3
user_agent = "WNBA-Analytics-Bot/1.0"

# File paths
data_dir = "wnba_game_data"
output_dir = "wnba_predictions"
model_dir = "wnba_models"
validation_dir = "wnba_validation"

[validation]
# Validation configuration
test_weeks = 4
min_train_weeks = 8
step_weeks = 2
n_validation_periods = 10

# Performance thresholds
target_brier_score = 0.12
min_r2_score = 0.5
target_coverage = 0.95

[dashboard]
# Streamlit dashboard configuration
page_title = "WNBA Daily Game Predictions"
page_icon = "🏀"
layout = "wide"
initial_sidebar_state = "expanded"

# Default settings
default_confidence_threshold = 0.7
show_uncertainties = true
auto_refresh_minutes = 60

[logging]
# Logging configuration
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
log_file = "wnba_predictions.log"
max_log_size_mb = 10
backup_count = 5